import type { App } from "@/types/database.types";

// FALLBACK_APPS — all apps seeded from legacy index.html
// Used when Supabase is unavailable (static export / offline build)
export const FALLBACK_APPS: App[] = [
  {
    id: "unmask", slug: "unmask", name: "Unmask · Purity & Power Companion",
    category_id: "spiritual", developer_id: null,
    url: "https://candanumut.github.io/Unmasking_sexual_engineered/",
    preview_url: "https://candanumut.github.io/Unmasking_sexual_engineered/",
    description_en: "Faith-friendly NoFap / reboot companion that shows how engineered sexual conditioning works, helps protect your brain and heart from harmful sexual content, and rebuilds a life of clarity, dignity, and worship. All plans, streaks, and notes stay fully local in your browser.",
    description_tr: "Mühendislik edilmiş cinsel koşullandırmanın nasıl işlediğini gösteren, zihnini ve kalbini zararlı cinsel içerikten korumana yardım eden iman dostu bir reboot rehberi.",
    tags_en: ["NoFap", "Faith", "Self-control", "Education"],
    tags_tr: ["NoFap", "İman", "Öz-denetim", "Eğitim"],
    platforms_en: ["Web"], platforms_tr: ["Web"],
    icon_filename: "spiritual-unmask.png", screenshots: [],
    is_published: true, is_featured: true, is_external: false,
    sort_order: 1, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "nova-arena-3d", slug: "nova-arena-3d", name: "Nova Arena 3D · Rogue Survivor",
    category_id: "games", developer_id: null,
    url: "https://candanumut.github.io/newbrotato/",
    preview_url: "https://candanumut.github.io/newbrotato/",
    description_en: "Top-down rogue-survivor in a Perlin-generated world of forests, rocks, lakes, and enemies. Dash, jump, experiment with different upgrades, and try to survive as long as possible in a living terrain that actually feels like ground.",
    description_tr: "Ormanlar, kayalar, göller ve düşmanlarla dolu Perlin üretimli bir dünyada yukarıdan görünüşlü rogue-survivor.",
    tags_en: ["Action", "Roguelite", "3D", "Prototype"], tags_tr: ["Aksiyon", "Roguelite", "3D", "Prototip"],
    platforms_en: ["Web"], platforms_tr: ["Web"],
    icon_filename: "games-nova-arena-3d.png", screenshots: [],
    is_published: true, is_featured: true, is_external: false,
    sort_order: 2, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "roulette-rooms", slug: "roulette-rooms", name: "Roulette Rooms · Online Russian Roulette",
    category_id: "games", developer_id: null,
    url: "https://candanumut.github.io/roulette",
    preview_url: "https://candanumut.github.io/roulette",
    description_en: "Online Russian roulette party game with smooth animations. Spin up a room in seconds, share the link with friends, follow the built-in instructions, and track rounds on a shared scoreboard.",
    description_tr: "Akıcı animasyonlara sahip çevrimiçi Rus ruleti parti oyunu.",
    tags_en: ["Multiplayer", "Party", "Rooms", "Scoreboard"], tags_tr: ["Çok oyunculu", "Parti", "Odalar", "Skor tablosu"],
    platforms_en: ["Web"], platforms_tr: ["Web"],
    icon_filename: "games-roulette-rooms.png", screenshots: [],
    is_published: true, is_featured: false, is_external: false,
    sort_order: 3, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "high-or-low", slug: "high-or-low", name: "High or Low · Live Card Guessing Rooms",
    category_id: "games", developer_id: null,
    url: "https://candanumut.github.io/Highorlow/",
    preview_url: "https://candanumut.github.io/Highorlow/",
    description_en: "Real-time card showdown where you and friends guess whether the next card will be higher, lower, or the same. Create a private room in seconds, watch turns update instantly, and enjoy a cozy multiplayer party game with no installs.",
    description_tr: "Bir sonraki kartın yüksek mi düşük mü aynı mı olacağını arkadaşlarınla anlık olarak tahmin et.",
    tags_en: ["Multiplayer", "Cards", "Guessing", "Real-time"], tags_tr: ["Çok oyunculu", "Kart", "Tahmin", "Anlık"],
    platforms_en: ["Web"], platforms_tr: ["Web"],
    icon_filename: "games-high-or-low.png", screenshots: [],
    is_published: true, is_featured: false, is_external: false,
    sort_order: 4, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "mathbomb", slug: "mathbomb", name: "MathBomb · Timed Math Dodgeball",
    category_id: "games", developer_id: null,
    url: "https://candanumut.github.io/Mathbomb/",
    preview_url: "https://candanumut.github.io/Mathbomb/",
    description_en: "Fast-paced online math duel. Answer the countdown question correctly to throw the bomb to the friend you choose; miss and it might explode in your hands.",
    description_tr: "Hızlı tempolu çevrimiçi matematik düellosu.",
    tags_en: ["Multiplayer", "Math", "Timer", "Party"], tags_tr: ["Çok oyunculu", "Matematik", "Zamanlayıcı", "Parti"],
    platforms_en: ["Web"], platforms_tr: ["Web"],
    icon_filename: "games-mathbomb.png", screenshots: [],
    is_published: true, is_featured: false, is_external: false,
    sort_order: 5, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "scale-universe", slug: "scale-universe", name: "Scale of the Universe · Tefekkür Tool",
    category_id: "learning", developer_id: null,
    url: "https://candanumut.github.io/Scaleuniverse/",
    preview_url: "https://candanumut.github.io/Scaleuniverse/",
    description_en: "An interactive visual journey from subatomic particles all the way to the edge of the observable universe. Designed for tefekkür and humility.",
    description_tr: "Atom altı parçacıklardan gözlemlenebilir evrenin sınırına uzanan etkileşimli bir görsel yolculuk.",
    tags_en: ["Education", "Cosmos", "Reflection", "Interactive"], tags_tr: ["Eğitim", "Kozmos", "Tefekkür", "Etkileşim"],
    platforms_en: ["Web"], platforms_tr: ["Web"],
    icon_filename: "learning-scale-universe.png", screenshots: [],
    is_published: true, is_featured: false, is_external: false,
    sort_order: 6, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "ready-to-die", slug: "ready-to-die", name: "Hereafter Readiness Assessment",
    category_id: "spiritual", developer_id: null,
    url: "https://candanumut.github.io/Readytodie/",
    preview_url: "https://candanumut.github.io/Readytodie/",
    description_en: "A Qur'an & Sunnah–inspired self-accounting tool. Reflect on faith, worship, character, rights of others, knowledge, tawba and sincerity.",
    description_tr: "Kur'an ve Sünnet'ten ilham alan bir muhasebe aracı.",
    tags_en: ["Faith", "Self-reflection", "Accountability"], tags_tr: ["İman", "Öz muhasebe", "Sorumluluk"],
    platforms_en: ["Web"], platforms_tr: ["Web"],
    icon_filename: "spiritual-ready-to-die.png", screenshots: [],
    is_published: true, is_featured: false, is_external: false,
    sort_order: 7, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "freedom-score", slug: "freedom-score", name: "Freedom Score — Addiction & Habit Self-Assessment",
    category_id: "self-assessment", developer_id: null,
    url: "https://candanumut.github.io/Addiction_test/",
    preview_url: "https://candanumut.github.io/Addiction_test/",
    description_en: "A private, browser-only addiction & habit self-check. 15 questions scan substances, phone & social media, gaming, food, lust, money, ego and spiritual grounding.",
    description_tr: "Tamamen tarayıcıda çalışan, gizli bir bağımlılık ve alışkanlık öz değerlendirme aracı.",
    tags_en: ["Addiction", "Habits", "Self-assessment", "Digital wellbeing"],
    tags_tr: ["Bağımlılık", "Alışkanlıklar", "Öz değerlendirme", "Dijital denge"],
    platforms_en: ["Web"], platforms_tr: ["Web"],
    icon_filename: "self-assessment-freedom-score.png", screenshots: [],
    is_published: true, is_featured: false, is_external: false,
    sort_order: 8, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "how-old", slug: "how-old", name: "Body & Mind Age Assessment",
    category_id: "wellness", developer_id: null,
    url: "https://candanumut.github.io/Howold/",
    preview_url: "https://candanumut.github.io/Howold/",
    description_en: "Science-inspired questionnaire to estimate your 'body age' and 'mind age' based on sleep, movement, nutrition, stress, habits, social life, and meaning.",
    description_tr: "Uyku, hareket, beslenme, stres, alışkanlıklar üzerinden 'beden yaşı' ve 'zihin yaşı' tahmini yapan bilim esintili bir anket.",
    tags_en: ["Health", "Psychology", "Habits", "Self-awareness"], tags_tr: ["Sağlık", "Psikoloji", "Alışkanlık", "Farkındalık"],
    platforms_en: ["Web"], platforms_tr: ["Web"],
    icon_filename: "wellness-how-old.png", screenshots: [],
    is_published: true, is_featured: false, is_external: false,
    sort_order: 9, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "manevi-farkindalik", slug: "manevi-farkindalik", name: "Manevî Farkındalık Rehberi",
    category_id: "spiritual", developer_id: null,
    url: "https://candanumut.github.io/hakikat_ucgeni/",
    preview_url: "https://candanumut.github.io/hakikat_ucgeni/",
    description_en: "Spiritual Awareness Companion that reminds you of the games of Shaytan, Nafs, and Dunya from a Qur'anic lens. Daily checklists, breathing exercises, notes, and protection tips.",
    description_tr: "Kur'an perspektifinden şeytan, nefis ve dünyanın oyunlarını hatırlatan Manevî Farkındalık Rehberi.",
    tags_en: ["Dhikr", "Mindfulness", "Checklist", "Protection"], tags_tr: ["Zikir", "Farkındalık", "Kontrol listesi", "Korunma"],
    platforms_en: ["Web"], platforms_tr: ["Web"],
    icon_filename: "spiritual-manevi-farkindalik.png", screenshots: [],
    is_published: true, is_featured: false, is_external: false,
    sort_order: 10, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "pru-universe-simulator", slug: "pru-universe-simulator", name: "PRU Universe Simulator · Cosmos Sandbox",
    category_id: "learning", developer_id: null,
    url: "https://candanumut.github.io/pru_simulation_engine/",
    preview_url: "https://candanumut.github.io/pru_simulation_engine/",
    description_en: "A 3D scientific visualization tool that lets you build star systems, watch galaxies form, and observe black holes through the Precomputed Relational Universe (PRU) model.",
    description_tr: "PRU modeliyle yıldız sistemleri kurmanı, galaksi oluşumunu izlemeni ve kara delik etkilerini gözlemlemeni sağlayan 3B bilimsel görselleştirme aracı.",
    tags_en: ["Simulation", "Cosmology", "3D", "Interactive"], tags_tr: ["Simülasyon", "Kozmoloji", "3D", "Etkileşim"],
    platforms_en: ["Web"], platforms_tr: ["Web"],
    icon_filename: "learning-pru-universe-simulator.png", screenshots: [],
    is_published: true, is_featured: false, is_external: false,
    sort_order: 11, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "takva-race", slug: "takva-race", name: "TakvaRace · Sprint Toward Goodness",
    category_id: "games", developer_id: null,
    url: "https://candanumut.github.io/adilstore-webapps/com.takvarace.takvarace/1.0.0/",
    preview_url: "https://candanumut.github.io/adilstore-webapps/com.takvarace.takvarace/1.0.0/",
    description_en: "A small arcade experiment from the Takva universe. Dash through a minimalist track while symbolically racing toward khayr and away from distractions.",
    description_tr: "Takva evreninden küçük bir arcade denemesi.",
    tags_en: ["Arcade", "Prototype", "Takva"], tags_tr: ["Arcade", "Prototip", "Takva"],
    platforms_en: ["Web", "Android (APK build)"], platforms_tr: ["Web", "Android (APK sürümü)"],
    icon_filename: "games-takva-race.png", screenshots: [],
    is_published: true, is_featured: false, is_external: false,
    sort_order: 12, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "dreamsleep", slug: "dreamsleep", name: "DreamSleep · Gentle Night Companion",
    category_id: "wellness", developer_id: null,
    url: "https://candanumut.github.io/adilstore-webapps/com.dreamsleep.dreamsleep/1.0.0/",
    preview_url: "https://candanumut.github.io/adilstore-webapps/com.dreamsleep.dreamsleep/1.0.0/",
    description_en: "A calm sleep helper focused on better nights and kinder mornings. Mix soothing sounds and intentional routines.",
    description_tr: "Daha iyi geceler ve daha yumuşak sabahlar için sakin bir uyku yardımcısı.",
    tags_en: ["Sleep", "Relaxation", "Routine"], tags_tr: ["Uyku", "Rahatlama", "Rutin"],
    platforms_en: ["Web build", "Android"], platforms_tr: ["Web sürümü", "Android"],
    icon_filename: "wellness-dreamsleep.png", screenshots: [],
    is_published: true, is_featured: false, is_external: false,
    sort_order: 13, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "pdf-reader", slug: "pdf-reader", name: "Minimalist PDF Reader",
    category_id: "tools", developer_id: null,
    url: "https://candanumut.github.io/adilstore-webapps/com.example.pdfreader/1.0.1/",
    preview_url: "https://candanumut.github.io/adilstore-webapps/com.example.pdfreader/1.0.1/",
    description_en: "Lightweight, distraction-free PDF reader. No ads, no analytics, no nonsense — just open your files and read.",
    description_tr: "Hafif ve dikkat dağıtmayan bir PDF okuyucu. Reklam yok, analitik yok.",
    tags_en: ["Productivity", "Reader", "Offline-friendly"], tags_tr: ["Verimlilik", "Okuyucu", "Çevrimdışı dostu"],
    platforms_en: ["Web build", "Android"], platforms_tr: ["Web sürümü", "Android"],
    icon_filename: "tools-pdf-reader.png", screenshots: [],
    is_published: true, is_featured: false, is_external: false,
    sort_order: 14, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "zikr-checker", slug: "zikr-checker", name: "ZikrChecker · Daily Remembrance Tracker",
    category_id: "spiritual", developer_id: null,
    url: "https://candanumut.github.io/adilstore-webapps/com.example.zikrchecker/1.0.9/",
    preview_url: "https://candanumut.github.io/adilstore-webapps/com.example.zikrchecker/1.0.9/",
    description_en: "A simple, focused dashboard to keep track of daily spiritual actions: istighfar, salawat, Qur'an reading, gratitude, and good deeds.",
    description_tr: "Günlük manevi amelleri takip etmek için sade bir pano.",
    tags_en: ["Dhikr", "Habits", "Dashboard"], tags_tr: ["Zikir", "Alışkanlık", "Pano"],
    platforms_en: ["Web build", "Android"], platforms_tr: ["Web sürümü", "Android"],
    icon_filename: "spiritual-zikr-checker.png", screenshots: [],
    is_published: true, is_featured: false, is_external: false,
    sort_order: 15, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "climate-change-dashboard", slug: "climate-change-dashboard", name: "Climate Change Awareness Dashboard",
    category_id: "environment", developer_id: null,
    url: "https://candanumut.github.io/Climatechange/",
    preview_url: "https://candanumut.github.io/Climatechange/",
    description_en: "A climate change awareness dashboard built on live weather and air-quality data. Explore temperature, rain, wind, air pollution and perceived risk.",
    description_tr: "Gerçek zamanlı hava durumu ve hava kalitesi verilerine dayalı bir iklim değişikliği farkındalık paneli.",
    tags_en: ["Climate change", "Environment", "Weather", "Air quality"],
    tags_tr: ["İklim değişikliği", "Çevre", "Hava durumu", "Hava kalitesi"],
    platforms_en: ["Web"], platforms_tr: ["Web"],
    icon_filename: "environment-climate-change-dashboard.png", screenshots: [],
    is_published: true, is_featured: false, is_external: false,
    sort_order: 16, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "healing-sounds", slug: "healing-sounds", name: "Healing Sounds · Frequency & Sound Baths",
    category_id: "wellness", developer_id: null,
    url: "https://play.google.com/store/apps/details?id=com.healing.healingsound.healingsounds",
    preview_url: null,
    description_en: "A collection of calming soundscapes, nature ambience, and frequency-based tracks to support focus, relaxation, and meditation.",
    description_tr: "Odaklanma, rahatlama ve meditasyonu desteklemek için sakinleştirici soundscape'ler.",
    tags_en: ["Sound therapy", "Meditation", "Relaxation"], tags_tr: ["Ses terapisi", "Meditasyon", "Rahatlama"],
    platforms_en: ["Android (Google Play)"], platforms_tr: ["Android (Google Play)"],
    icon_filename: "wellness-healing-sounds.png", screenshots: [],
    is_published: true, is_featured: false, is_external: true,
    sort_order: 17, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "awakening", slug: "awakening", name: "Awakening · Mindful Wake-Up",
    category_id: "wellness", developer_id: null,
    url: "https://play.google.com/store/apps/details?id=com.wakeup.wakeup.awakening",
    preview_url: null,
    description_en: "A meditation-first wake-up app. Instead of starting the day with chaos and social feeds, Awakening invites you to breathe, remember your values, and step into the morning with clarity and gratitude.",
    description_tr: "Güne meditasyonla başlaman için bir alarm uygulaması.",
    tags_en: ["Meditation", "Morning routine", "Mindfulness"], tags_tr: ["Meditasyon", "Sabah rutini", "Farkındalık"],
    platforms_en: ["Android (Google Play)"], platforms_tr: ["Android (Google Play)"],
    icon_filename: "wellness-awakening.png", screenshots: [],
    is_published: true, is_featured: false, is_external: true,
    sort_order: 18, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "hopy-tower-3", slug: "hopy-tower-3", name: "Hopy Tower 3 · Vertical Challenge",
    category_id: "games", developer_id: null,
    url: "https://play.google.com/store/apps/details?id=com.hopy_tower3.hopy.hopy_tower3",
    preview_url: null,
    description_en: "Fast, vertical arcade game where you climb a colorful tower, time your jumps, and try not to fall.",
    description_tr: "Renkli bir kuleyi tırmandığın, zıplamalarını zamanladığın ve düşmemeye çalıştığın hızlı bir dikey arcade oyunu.",
    tags_en: ["Arcade", "Casual", "Mobile"], tags_tr: ["Arcade", "Gündelik", "Mobil"],
    platforms_en: ["Android (Google Play)"], platforms_tr: ["Android (Google Play)"],
    icon_filename: "games-hopy-tower-3.png", screenshots: [],
    is_published: true, is_featured: false, is_external: true,
    sort_order: 19, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "quizroom", slug: "quizroom", name: "QuizRoom · Live Multiplayer Quiz",
    category_id: "games", developer_id: null,
    url: "https://candanumut.github.io/quizroom/",
    preview_url: "https://candanumut.github.io/quizroom/",
    description_en: "Real-time quiz battle with rooms. Create a quiz, invite friends, and compete live without any installs.",
    description_tr: "Gerçek zamanlı soru-cevap yarışması. Oda aç, arkadaşlarını davet et, kurulum gerektirmeden yarış.",
    tags_en: ["Quiz", "Multiplayer", "Real-time"], tags_tr: ["Bilgi yarışması", "Çok oyunculu", "Anlık"],
    platforms_en: ["Web"], platforms_tr: ["Web"],
    icon_filename: "games-quizroom.png", screenshots: [],
    is_published: true, is_featured: false, is_external: false,
    sort_order: 20, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "joplin-notes", slug: "joplin-notes", name: "Joplin · Encrypted Notes & To-Dos",
    category_id: "tools", developer_id: null,
    url: "https://joplinapp.org/",
    preview_url: "https://joplinapp.org/",
    description_en: "Open-source notes and to-do app with end-to-end encryption, Markdown, notebooks and tags. Sync via Joplin Cloud or your own Nextcloud/WebDAV.",
    description_tr: "Uçtan uca şifreleme, Markdown, defterler ve etiketler sunan açık kaynaklı not ve yapılacaklar uygulaması.",
    tags_en: ["Open-source", "Encrypted", "Markdown", "Sync"],
    tags_tr: ["Açık kaynak", "Şifreli", "Markdown", "Eşitleme"],
    platforms_en: ["Windows", "macOS", "Linux", "Android", "iOS"],
    platforms_tr: ["Windows", "macOS", "Linux", "Android", "iOS"],
    icon_filename: "tools-joplin-notes.png", screenshots: [],
    is_published: true, is_featured: false, is_external: true,
    sort_order: 21, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "standard-notes", slug: "standard-notes", name: "Standard Notes · Long-term Notes Vault",
    category_id: "tools", developer_id: null,
    url: "https://standardnotes.com/",
    preview_url: "https://standardnotes.com/",
    description_en: "Zero-knowledge encrypted note system with simple core and powerful optional editors. Built for 10+ years of safe note-keeping.",
    description_tr: "Sıfır bilgi şifrelemeli, sade ama güçlü editörlere sahip not sistemi.",
    tags_en: ["Encrypted", "Open-source", "Long-term", "Sync"],
    tags_tr: ["Şifreli", "Açık kaynak", "Uzun vadeli", "Eşitleme"],
    platforms_en: ["Web", "Windows", "macOS", "Linux", "Android", "iOS"],
    platforms_tr: ["Web", "Windows", "macOS", "Linux", "Android", "iOS"],
    icon_filename: "tools-standard-notes.png", screenshots: [],
    is_published: true, is_featured: false, is_external: true,
    sort_order: 22, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "proton-mail", slug: "proton-mail", name: "Proton Mail · Encrypted Email",
    category_id: "tools", developer_id: null,
    url: "https://proton.me/mail",
    preview_url: "https://proton.me/mail",
    description_en: "End-to-end encrypted email from Proton's privacy suite. Open-source apps, zero-access encryption and servers in Switzerland.",
    description_tr: "Proton'un mahremiyet odaklı paketinden uçtan uca şifreli e-posta.",
    tags_en: ["Email", "Encrypted", "Open-source", "Privacy"],
    tags_tr: ["E-posta", "Şifreli", "Açık kaynak", "Mahremiyet"],
    platforms_en: ["Web", "Android", "iOS"], platforms_tr: ["Web", "Android", "iOS"],
    icon_filename: "tools-proton-mail.png", screenshots: [],
    is_published: true, is_featured: false, is_external: true,
    sort_order: 23, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "tuta-mail", slug: "tuta-mail", name: "Tuta · Private Mail & Calendar",
    category_id: "tools", developer_id: null,
    url: "https://tuta.com/",
    preview_url: "https://tuta.com/",
    description_en: "Open-source, end-to-end encrypted email and calendar with a clean interface. Based in Germany with a strong no-tracking, no-ads stance.",
    description_tr: "Açık kaynaklı, uçtan uca şifreli e-posta ve takvim.",
    tags_en: ["Email", "Calendar", "Encrypted", "Open-source"],
    tags_tr: ["E-posta", "Takvim", "Şifreli", "Açık kaynak"],
    platforms_en: ["Web", "Android", "iOS"], platforms_tr: ["Web", "Android", "iOS"],
    icon_filename: "tools-tuta-mail.png", screenshots: [],
    is_published: true, is_featured: false, is_external: true,
    sort_order: 24, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "proton-drive", slug: "proton-drive", name: "Proton Drive · Encrypted Cloud Storage",
    category_id: "tools", developer_id: null,
    url: "https://proton.me/drive",
    preview_url: "https://proton.me/drive",
    description_en: "End-to-end encrypted cloud storage and file sharing from the Proton ecosystem.",
    description_tr: "Proton ekosisteminden uçtan uca şifreli bulut depolama ve dosya paylaşımı.",
    tags_en: ["Cloud", "Encrypted", "Files", "Backup"],
    tags_tr: ["Bulut", "Şifreli", "Dosyalar", "Yedekleme"],
    platforms_en: ["Web", "Windows", "macOS", "Android", "iOS"],
    platforms_tr: ["Web", "Windows", "macOS", "Android", "iOS"],
    icon_filename: "tools-proton-drive.png", screenshots: [],
    is_published: true, is_featured: false, is_external: true,
    sort_order: 25, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "bitwarden", slug: "bitwarden", name: "Bitwarden · Password Manager",
    category_id: "tools", developer_id: null,
    url: "https://bitwarden.com/",
    preview_url: "https://vault.bitwarden.com/#/register",
    description_en: "Open-source, zero-knowledge password manager with vault sharing and two factor support.",
    description_tr: "Açık kaynaklı, sıfır bilgi parola yöneticisi.",
    tags_en: ["Passwords", "Security", "Open-source", "Privacy"],
    tags_tr: ["Parolalar", "Güvenlik", "Açık kaynak", "Mahremiyet"],
    platforms_en: ["Web", "Browser extensions", "Windows", "macOS", "Linux", "Android", "iOS"],
    platforms_tr: ["Web", "Tarayıcı eklentileri", "Windows", "macOS", "Linux", "Android", "iOS"],
    icon_filename: "tools-bitwarden.png", screenshots: [],
    is_published: true, is_featured: false, is_external: true,
    sort_order: 26, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "nextcloud-hub", slug: "nextcloud-hub", name: "Nextcloud Hub · Self-hosted Cloud",
    category_id: "tools", developer_id: null,
    url: "https://nextcloud.com/",
    preview_url: "https://nextcloud.com/",
    description_en: "Full open-source cloud you can self-host: files, photos, calendar, contacts, tasks and more.",
    description_tr: "Kendin barındırabildiğin tam açık kaynak bulut.",
    tags_en: ["Self-hosted", "Cloud", "Files", "Calendar"],
    tags_tr: ["Kendi sunucun", "Bulut", "Dosyalar", "Takvim"],
    platforms_en: ["Web", "Android", "iOS", "Desktop sync apps"],
    platforms_tr: ["Web", "Android", "iOS", "Masaüstü istemciler"],
    icon_filename: "tools-nextcloud-hub.png", screenshots: [],
    is_published: true, is_featured: false, is_external: true,
    sort_order: 27, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "openstreetmap", slug: "openstreetmap", name: "OpenStreetMap · Community-powered Maps",
    category_id: "tools", developer_id: null,
    url: "https://www.openstreetmap.org/",
    preview_url: "https://www.openstreetmap.org/",
    description_en: "Collaboratively edited world map. Anonymous to use, free to embed, and improved by volunteers instead of ad-tech.",
    description_tr: "Gönüllüler tarafından birlikte düzenlenen dünya haritası.",
    tags_en: ["Maps", "Open data", "Navigation"],
    tags_tr: ["Haritalar", "Açık veri", "Navigasyon"],
    platforms_en: ["Web", "Mobile apps via many clients"],
    platforms_tr: ["Web", "Birçok istemci üzerinden mobil uygulamalar"],
    icon_filename: "tools-openstreetmap.png", screenshots: [],
    is_published: true, is_featured: false, is_external: true,
    sort_order: 28, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "cryptpad", slug: "cryptpad", name: "CryptPad · Encrypted Docs & Boards",
    category_id: "tools", developer_id: null,
    url: "https://cryptpad.fr/",
    preview_url: "https://cryptpad.fr/",
    description_en: "Open-source, end-to-end encrypted collaboration suite: notes, docs, sheets, kanban, whiteboards and more.",
    description_tr: "Notlar, belgeler, tablolar, kanban panoları, beyaz tahta sunan açık kaynaklı, uçtan uca şifreli işbirliği paketi.",
    tags_en: ["Collaboration", "Encrypted", "Docs", "Open-source"],
    tags_tr: ["İşbirliği", "Şifreli", "Belgeler", "Açık kaynak"],
    platforms_en: ["Web"], platforms_tr: ["Web"],
    icon_filename: "tools-cryptpad.png", screenshots: [],
    is_published: true, is_featured: false, is_external: true,
    sort_order: 29, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "collabora-online", slug: "collabora-online", name: "Collabora Online · LibreOffice in the Browser",
    category_id: "tools", developer_id: null,
    url: "https://www.collaboraonline.com/",
    preview_url: "https://www.collaboraonline.com/",
    description_en: "LibreOffice-based online office suite for documents, spreadsheets and presentations with real-time collaboration.",
    description_tr: "Belgeler, tablolar ve sunumlar için gerçek zamanlı işbirliği sunan, LibreOffice tabanlı çevrimiçi ofis paketi.",
    tags_en: ["Office", "Collaboration", "Open-source"],
    tags_tr: ["Ofis", "İşbirliği", "Açık kaynak"],
    platforms_en: ["Web", "Self-hosted"], platforms_tr: ["Web", "Kendi sunucun"],
    icon_filename: "tools-collabora-online.png", screenshots: [],
    is_published: true, is_featured: false, is_external: true,
    sort_order: 30, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "breath-aurora", slug: "breath-aurora", name: "Breath Aurora · Guided Breathing",
    category_id: "wellness", developer_id: null,
    url: "https://candanumut.github.io/breath-aurora/",
    preview_url: "https://candanumut.github.io/breath-aurora/",
    description_en: "Calm, visual breathing guide with customizable patterns for stress relief, focus, and pre-sleep relaxation. No account, no data collection.",
    description_tr: "Stres azaltma, odaklanma ve uyku öncesi rahatlama için özelleştirilebilir nefes rehberi.",
    tags_en: ["Breathing", "Mindfulness", "Relaxation"], tags_tr: ["Nefes", "Farkındalık", "Rahatlama"],
    platforms_en: ["Web"], platforms_tr: ["Web"],
    icon_filename: "wellness-breath-aurora.png", screenshots: [],
    is_published: true, is_featured: false, is_external: false,
    sort_order: 31, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "marifah", slug: "marifah", name: "Marifah · Islamic Knowledge Companion",
    category_id: "spiritual", developer_id: null,
    url: "https://candanumut.github.io/marifah/",
    preview_url: "https://candanumut.github.io/marifah/",
    description_en: "A structured Islamic knowledge companion covering aqeedah, fiqh, seerah, and daily supplications. Designed for gradual, consistent learning.",
    description_tr: "Akide, fıkıh, siyer ve günlük duaları kapsayan yapılandırılmış bir İslami ilim rehberi.",
    tags_en: ["Islamic knowledge", "Aqeedah", "Dua", "Learning"],
    tags_tr: ["İslami ilim", "Akide", "Dua", "Öğrenme"],
    platforms_en: ["Web"], platforms_tr: ["Web"],
    icon_filename: "spiritual-marifah.png", screenshots: [],
    is_published: true, is_featured: false, is_external: false,
    sort_order: 32, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "pomodoro-circle", slug: "pomodoro-circle", name: "Pomodoro Circle · Focus Timer",
    category_id: "tools", developer_id: null,
    url: "https://candanumut.github.io/pomodoro/",
    preview_url: "https://candanumut.github.io/pomodoro/",
    description_en: "Clean, distraction-free Pomodoro timer with customizable intervals. Works offline, no account required, no data sent.",
    description_tr: "Özelleştirilebilir aralıklara sahip sade, dikkat dağıtmayan Pomodoro zamanlayıcısı.",
    tags_en: ["Productivity", "Focus", "Timer", "Offline"],
    tags_tr: ["Verimlilik", "Odaklanma", "Zamanlayıcı", "Çevrimdışı"],
    platforms_en: ["Web"], platforms_tr: ["Web"],
    icon_filename: "productivity-pomodoro-circle.png", screenshots: [],
    is_published: true, is_featured: false, is_external: false,
    sort_order: 33, install_count: 0, ranking_score: 0, version: null,
    created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-01-01T00:00:00.000Z",
  },
];

export const FALLBACK_APP_SLUGS = FALLBACK_APPS.map((a) => a.slug);
