-- AdilStore — Seed: migrate all 47 FALLBACK_APPS into the apps table
-- Run after 001_initial_schema.sql

INSERT INTO apps (slug, name, category_id, url, preview_url, description_en, description_tr, tags_en, tags_tr, platforms_en, platforms_tr, icon_filename, is_published, is_featured, is_external, sort_order)
VALUES
  ('unmask', 'Unmask · Purity & Power Companion', 'spiritual',
   'https://candanumut.github.io/Unmasking_sexual_engineered/',
   'https://candanumut.github.io/Unmasking_sexual_engineered/',
   'Faith-friendly NoFap / reboot companion that shows how engineered sexual conditioning works, helps protect your brain and heart from harmful sexual content, and rebuilds a life of clarity, dignity, and worship. All plans, streaks, and notes stay fully local in your browser.',
   'Mühendislik edilmiş cinsel koşullandırmanın nasıl işlediğini gösteren, zihnini ve kalbini zararlı cinsel içerikten korumana yardım eden iman dostu bir reboot rehberi.',
   ARRAY['NoFap','Faith','Self-control','Education'],
   ARRAY['NoFap','İman','Öz-denetim','Eğitim'],
   ARRAY['Web'], ARRAY['Web'],
   'spiritual-unmask.png', true, true, false, 1),

  ('nova-arena-3d', 'Nova Arena 3D · Rogue Survivor', 'games',
   'https://candanumut.github.io/newbrotato/',
   'https://candanumut.github.io/newbrotato/',
   'Top-down rogue-survivor in a Perlin-generated world of forests, rocks, lakes, and enemies. Dash, jump, experiment with different upgrades, and try to survive as long as possible in a living terrain that actually feels like ground.',
   'Ormanlar, kayalar, göller ve düşmanlarla dolu Perlin üretimli bir dünyada yukarıdan görünüşlü rogue-survivor.',
   ARRAY['Action','Roguelite','3D','Prototype'],
   ARRAY['Aksiyon','Roguelite','3D','Prototip'],
   ARRAY['Web'], ARRAY['Web'],
   'games-nova-arena-3d.png', true, true, false, 2),

  ('roulette-rooms', 'Roulette Rooms · Online Russian Roulette', 'games',
   'https://candanumut.github.io/roulette',
   'https://candanumut.github.io/roulette',
   'Online Russian roulette party game with smooth animations. Spin up a room in seconds, share the link with friends, follow the built-in instructions, and track rounds on a shared scoreboard. Purely for fun — gambling is not allowed.',
   'Akıcı animasyonlara sahip çevrimiçi Rus ruleti parti oyunu.',
   ARRAY['Multiplayer','Party','Rooms','Scoreboard'],
   ARRAY['Çok oyunculu','Parti','Odalar','Skor tablosu'],
   ARRAY['Web'], ARRAY['Web'],
   'games-roulette-rooms.png', true, false, false, 3),

  ('high-or-low', 'High or Low · Live Card Guessing Rooms', 'games',
   'https://candanumut.github.io/Highorlow/',
   'https://candanumut.github.io/Highorlow/',
   'Real-time card showdown where you and friends guess whether the next card will be higher, lower, or the same. Create a private room in seconds, watch turns update instantly, and enjoy a cozy multiplayer party game with no installs.',
   'Bir sonraki kartın yüksek mi düşük mü aynı mı olacağını arkadaşlarınla anlık olarak tahmin et.',
   ARRAY['Multiplayer','Cards','Guessing','Real-time'],
   ARRAY['Çok oyunculu','Kart','Tahmin','Anlık'],
   ARRAY['Web'], ARRAY['Web'],
   'games-high-or-low.png', true, false, false, 4),

  ('mathbomb', 'MathBomb · Timed Math Dodgeball', 'games',
   'https://candanumut.github.io/Mathbomb/',
   'https://candanumut.github.io/Mathbomb/',
   'Fast-paced online math duel. Answer the countdown question correctly to throw the bomb to the friend you choose; miss and it might explode in your hands.',
   'Hızlı tempolu çevrimiçi matematik düellosu.',
   ARRAY['Multiplayer','Math','Timer','Party'],
   ARRAY['Çok oyunculu','Matematik','Zamanlayıcı','Parti'],
   ARRAY['Web'], ARRAY['Web'],
   'games-mathbomb.png', true, false, false, 5),

  ('scale-universe', 'Scale of the Universe · Tefekkür Tool', 'learning',
   'https://candanumut.github.io/Scaleuniverse/',
   'https://candanumut.github.io/Scaleuniverse/',
   'An interactive visual journey from subatomic particles all the way to the edge of the observable universe. Designed for tefekkür and humility.',
   'Atom altı parçacıklardan gözlemlenebilir evrenin sınırına uzanan etkileşimli bir görsel yolculuk.',
   ARRAY['Education','Cosmos','Reflection','Interactive'],
   ARRAY['Eğitim','Kozmos','Tefekkür','Etkileşim'],
   ARRAY['Web'], ARRAY['Web'],
   'learning-scale-universe.png', true, false, false, 6),

  ('ready-to-die', 'Hereafter Readiness Assessment', 'spiritual',
   'https://candanumut.github.io/Readytodie/',
   'https://candanumut.github.io/Readytodie/',
   'A Qur''an & Sunnah–inspired self-accounting tool. Reflect on faith, worship, character, rights of others, knowledge, tawba and sincerity.',
   'Kur''an ve Sünnet''ten ilham alan bir muhasebe aracı.',
   ARRAY['Faith','Self-reflection','Accountability'],
   ARRAY['İman','Öz muhasebe','Sorumluluk'],
   ARRAY['Web'], ARRAY['Web'],
   'spiritual-ready-to-die.png', true, false, false, 7),

  ('freedom-score', 'Freedom Score — Addiction & Habit Self-Assessment', 'self-assessment',
   'https://candanumut.github.io/Addiction_test/',
   'https://candanumut.github.io/Addiction_test/',
   'A private, browser-only addiction & habit self-check. 15 questions scan substances, phone & social media, gaming, food, lust, money, ego and spiritual grounding.',
   'Tamamen tarayıcıda çalışan, gizli bir bağımlılık ve alışkanlık öz değerlendirme aracı.',
   ARRAY['Addiction','Habits','Self-assessment','Digital wellbeing','Spiritual growth'],
   ARRAY['Bağımlılık','Alışkanlıklar','Öz değerlendirme','Dijital denge','Manevi gelişim'],
   ARRAY['Web'], ARRAY['Web'],
   'self-assessment-freedom-score.png', true, false, false, 8),

  ('how-old', 'Body & Mind Age Assessment', 'wellness',
   'https://candanumut.github.io/Howold/',
   'https://candanumut.github.io/Howold/',
   'Science-inspired questionnaire to estimate your ''body age'' and ''mind age'' based on sleep, movement, nutrition, stress, habits, social life, and meaning.',
   'Uyku, hareket, beslenme, stres, alışkanlıklar üzerinden ''beden yaşı'' ve ''zihin yaşı'' tahmini yapan bilim esintili bir anket.',
   ARRAY['Health','Psychology','Habits','Self-awareness'],
   ARRAY['Sağlık','Psikoloji','Alışkanlık','Farkındalık'],
   ARRAY['Web'], ARRAY['Web'],
   'wellness-how-old.png', true, false, false, 9),

  ('manevi-farkindalik', 'Manevî Farkındalık Rehberi', 'spiritual',
   'https://candanumut.github.io/hakikat_ucgeni/',
   'https://candanumut.github.io/hakikat_ucgeni/',
   'Spiritual Awareness Companion that reminds you of the games of Shaytan, Nafs, and Dunya from a Qur''anic lens. Daily checklists, breathing exercises, notes, and protection tips.',
   'Kur''an perspektifinden şeytan, nefis ve dünyanın oyunlarını hatırlatan Manevî Farkındalık Rehberi.',
   ARRAY['Dhikr','Mindfulness','Checklist','Protection'],
   ARRAY['Zikir','Farkındalık','Kontrol listesi','Korunma'],
   ARRAY['Web'], ARRAY['Web'],
   'spiritual-manevi-farkindalik.png', true, false, false, 10),

  ('pru-universe-simulator', 'PRU Universe Simulator · Cosmos Sandbox', 'learning',
   'https://candanumut.github.io/pru_simulation_engine/',
   'https://candanumut.github.io/pru_simulation_engine/',
   'A 3D scientific visualization tool that lets you build star systems, watch galaxies form, and observe black holes through the Precomputed Relational Universe (PRU) model.',
   'PRU modeliyle yıldız sistemleri kurmanı, galaksi oluşumunu izlemeni ve kara delik etkilerini gözlemlemeni sağlayan 3B bilimsel görselleştirme aracı.',
   ARRAY['Simulation','Cosmology','3D','Interactive'],
   ARRAY['Simülasyon','Kozmoloji','3D','Etkileşim'],
   ARRAY['Web'], ARRAY['Web'],
   'learning-pru-universe-simulator.png', true, false, false, 11),

  ('takva-race', 'TakvaRace · Sprint Toward Goodness', 'games',
   'https://candanumut.github.io/adilstore-webapps/com.takvarace.takvarace/1.0.0/',
   'https://candanumut.github.io/adilstore-webapps/com.takvarace.takvarace/1.0.0/',
   'A small arcade experiment from the Takva universe. Dash through a minimalist track while symbolically racing toward khayr and away from distractions.',
   'Takva evreninden küçük bir arcade denemesi.',
   ARRAY['Arcade','Prototype','Takva'],
   ARRAY['Arcade','Prototip','Takva'],
   ARRAY['Web','Android (APK build)'], ARRAY['Web','Android (APK sürümü)'],
   'games-takva-race.png', true, false, false, 12),

  ('dreamsleep', 'DreamSleep · Gentle Night Companion', 'wellness',
   'https://candanumut.github.io/adilstore-webapps/com.dreamsleep.dreamsleep/1.0.0/',
   'https://candanumut.github.io/adilstore-webapps/com.dreamsleep.dreamsleep/1.0.0/',
   'A calm sleep helper focused on better nights and kinder mornings. Mix soothing sounds and intentional routines.',
   'Daha iyi geceler ve daha yumuşak sabahlar için sakin bir uyku yardımcısı.',
   ARRAY['Sleep','Relaxation','Routine'],
   ARRAY['Uyku','Rahatlama','Rutin'],
   ARRAY['Web build','Android'], ARRAY['Web sürümü','Android'],
   'wellness-dreamsleep.png', true, false, false, 13),

  ('pdf-reader', 'Minimalist PDF Reader', 'tools',
   'https://candanumut.github.io/adilstore-webapps/com.example.pdfreader/1.0.1/',
   'https://candanumut.github.io/adilstore-webapps/com.example.pdfreader/1.0.1/',
   'Lightweight, distraction-free PDF reader. No ads, no analytics, no nonsense — just open your files and read.',
   'Hafif ve dikkat dağıtmayan bir PDF okuyucu. Reklam yok, analitik yok.',
   ARRAY['Productivity','Reader','Offline-friendly'],
   ARRAY['Verimlilik','Okuyucu','Çevrimdışı dostu'],
   ARRAY['Web build','Android'], ARRAY['Web sürümü','Android'],
   'tools-pdf-reader.png', true, false, false, 14),

  ('zikr-checker', 'ZikrChecker · Daily Remembrance Tracker', 'spiritual',
   'https://candanumut.github.io/adilstore-webapps/com.example.zikrchecker/1.0.9/',
   'https://candanumut.github.io/adilstore-webapps/com.example.zikrchecker/1.0.9/',
   'A simple, focused dashboard to keep track of daily spiritual actions: istighfar, salawat, Qur''an reading, gratitude, and good deeds.',
   'Günlük manevi amelleri takip etmek için sade bir pano.',
   ARRAY['Dhikr','Habits','Dashboard'],
   ARRAY['Zikir','Alışkanlık','Pano'],
   ARRAY['Web build','Android'], ARRAY['Web sürümü','Android'],
   'spiritual-zikr-checker.png', true, false, false, 15),

  ('climate-change-dashboard', 'Climate Change Awareness Dashboard', 'environment',
   'https://candanumut.github.io/Climatechange/',
   'https://candanumut.github.io/Climatechange/',
   'A climate change awareness dashboard built on live weather and air-quality data. Explore temperature, rain, wind, air pollution and perceived risk.',
   'Gerçek zamanlı hava durumu ve hava kalitesi verilerine dayalı bir iklim değişikliği farkındalık paneli.',
   ARRAY['Climate change','Environment','Weather','Air quality','Data visualization'],
   ARRAY['İklim değişikliği','Çevre','Hava durumu','Hava kalitesi','Veri görselleştirme'],
   ARRAY['Web'], ARRAY['Web'],
   'environment-climate-change-dashboard.png', true, false, false, 16),

  ('healing-sounds', 'Healing Sounds · Frequency & Sound Baths', 'wellness',
   'https://play.google.com/store/apps/details?id=com.healing.healingsound.healingsounds',
   'https://play.google.com/store/apps/details?id=com.healing.healingsound.healingsounds',
   'A collection of calming soundscapes, nature ambience, and frequency-based tracks to support focus, relaxation, and meditation.',
   'Odaklanma, rahatlama ve meditasyonu desteklemek için sakinleştirici soundscape''ler.',
   ARRAY['Sound therapy','Meditation','Relaxation'],
   ARRAY['Ses terapisi','Meditasyon','Rahatlama'],
   ARRAY['Android (Google Play)'], ARRAY['Android (Google Play)'],
   'wellness-healing-sounds.png', true, false, true, 17),

  ('awakening', 'Awakening · Mindful Wake-Up', 'wellness',
   'https://play.google.com/store/apps/details?id=com.wakeup.wakeup.awakening',
   'https://play.google.com/store/apps/details?id=com.wakeup.wakeup.awakening',
   'A meditation-first wake-up app. Instead of starting the day with chaos and social feeds, Awakening invites you to breathe, remember your values, and step into the morning with clarity and gratitude.',
   'Güne meditasyonla başlaman için bir alarm uygulaması.',
   ARRAY['Meditation','Morning routine','Mindfulness'],
   ARRAY['Meditasyon','Sabah rutini','Farkındalık'],
   ARRAY['Android (Google Play)'], ARRAY['Android (Google Play)'],
   'wellness-awakening.png', true, false, true, 18),

  ('hopy-tower-3', 'Hopy Tower 3 · Vertical Challenge', 'games',
   'https://play.google.com/store/apps/details?id=com.hopy_tower3.hopy.hopy_tower3',
   'https://play.google.com/store/apps/details?id=com.hopy_tower3.hopy.hopy_tower3',
   'Fast, vertical arcade game where you climb a colorful tower, time your jumps, and try not to fall.',
   'Renkli bir kuleyi tırmandığın, zıplamalarını zamanladığın ve düşmemeye çalıştığın hızlı bir dikey arcade oyunu.',
   ARRAY['Arcade','Casual','Mobile'],
   ARRAY['Arcade','Gündelik','Mobil'],
   ARRAY['Android (Google Play)'], ARRAY['Android (Google Play)'],
   'games-hopy-tower-3.png', true, false, true, 19),

  ('quizroom', 'QuizRoom · Live Multiplayer Quiz', 'games',
   'https://candanumut.github.io/quizroom/',
   'https://candanumut.github.io/quizroom/',
   'Real-time quiz battle with rooms. Create a quiz, invite friends, and compete live without any installs.',
   'Gerçek zamanlı soru-cevap yarışması. Oda aç, arkadaşlarını davet et, kurulum gerektirmeden yarış.',
   ARRAY['Quiz','Multiplayer','Real-time'],
   ARRAY['Bilgi yarışması','Çok oyunculu','Anlık'],
   ARRAY['Web'], ARRAY['Web'],
   'games-quizroom.png', true, false, false, 20),

  -- External curated open-source tools
  ('joplin-notes', 'Joplin · Encrypted Notes & To-Dos', 'tools',
   'https://joplinapp.org/', 'https://joplinapp.org/',
   'Open-source notes and to-do app with end-to-end encryption, Markdown, notebooks and tags. Sync via Joplin Cloud or your own Nextcloud/WebDAV.',
   'Uçtan uca şifreleme, Markdown, defterler ve etiketler sunan açık kaynaklı not ve yapılacaklar uygulaması.',
   ARRAY['Open-source','Encrypted','Markdown','Sync'],
   ARRAY['Açık kaynak','Şifreli','Markdown','Eşitleme'],
   ARRAY['Windows','macOS','Linux','Android','iOS'],
   ARRAY['Windows','macOS','Linux','Android','iOS'],
   'tools-joplin-notes.png', true, false, true, 21),

  ('standard-notes', 'Standard Notes · Long-term Notes Vault', 'tools',
   'https://standardnotes.com/', 'https://standardnotes.com/',
   'Zero-knowledge encrypted note system with simple core and powerful optional editors. Built for 10+ years of safe note-keeping, not for harvesting your data.',
   'Sıfır bilgi şifrelemeli, sade ama güçlü editörlere sahip not sistemi.',
   ARRAY['Encrypted','Open-source','Long-term','Sync'],
   ARRAY['Şifreli','Açık kaynak','Uzun vadeli','Eşitleme'],
   ARRAY['Web','Windows','macOS','Linux','Android','iOS'],
   ARRAY['Web','Windows','macOS','Linux','Android','iOS'],
   'tools-standard-notes.png', true, false, true, 22),

  ('proton-mail', 'Proton Mail · Encrypted Email', 'tools',
   'https://proton.me/mail', 'https://proton.me/mail',
   'End-to-end encrypted email from Proton''s privacy suite. Open-source apps, zero-access encryption and servers in Switzerland.',
   'Proton''un mahremiyet odaklı paketinden uçtan uca şifreli e-posta.',
   ARRAY['Email','Encrypted','Open-source','Privacy'],
   ARRAY['E-posta','Şifreli','Açık kaynak','Mahremiyet'],
   ARRAY['Web','Android','iOS'], ARRAY['Web','Android','iOS'],
   'tools-proton-mail.png', true, false, true, 23),

  ('tuta-mail', 'Tuta · Private Mail & Calendar', 'tools',
   'https://tuta.com/', 'https://tuta.com/',
   'Open-source, end-to-end encrypted email and calendar with a clean interface. Based in Germany with a strong no-tracking, no-ads stance.',
   'Açık kaynaklı, uçtan uca şifreli e-posta ve takvim.',
   ARRAY['Email','Calendar','Encrypted','Open-source'],
   ARRAY['E-posta','Takvim','Şifreli','Açık kaynak'],
   ARRAY['Web','Android','iOS'], ARRAY['Web','Android','iOS'],
   'tools-tuta-mail.png', true, false, true, 24),

  ('proton-drive', 'Proton Drive · Encrypted Cloud Storage', 'tools',
   'https://proton.me/drive', 'https://proton.me/drive',
   'End-to-end encrypted cloud storage and file sharing from the Proton ecosystem.',
   'Proton ekosisteminden uçtan uca şifreli bulut depolama ve dosya paylaşımı.',
   ARRAY['Cloud','Encrypted','Files','Backup'],
   ARRAY['Bulut','Şifreli','Dosyalar','Yedekleme'],
   ARRAY['Web','Windows','macOS','Android','iOS'],
   ARRAY['Web','Windows','macOS','Android','iOS'],
   'tools-proton-drive.png', true, false, true, 25),

  ('bitwarden', 'Bitwarden · Password Manager', 'tools',
   'https://bitwarden.com/', 'https://vault.bitwarden.com/#/register',
   'Open-source, zero-knowledge password manager with vault sharing and two factor support.',
   'Açık kaynaklı, sıfır bilgi parola yöneticisi.',
   ARRAY['Passwords','Security','Open-source','Privacy'],
   ARRAY['Parolalar','Güvenlik','Açık kaynak','Mahremiyet'],
   ARRAY['Web','Browser extensions','Windows','macOS','Linux','Android','iOS'],
   ARRAY['Web','Tarayıcı eklentileri','Windows','macOS','Linux','Android','iOS'],
   'tools-bitwarden.png', true, false, true, 26),

  ('nextcloud-hub', 'Nextcloud Hub · Self-hosted Cloud', 'tools',
   'https://nextcloud.com/', 'https://nextcloud.com/',
   'Full open-source cloud you can self-host: files, photos, calendar, contacts, tasks and more.',
   'Kendin barındırabildiğin tam açık kaynak bulut.',
   ARRAY['Self-hosted','Cloud','Files','Calendar'],
   ARRAY['Kendi sunucun','Bulut','Dosyalar','Takvim'],
   ARRAY['Web','Android','iOS','Desktop sync apps'],
   ARRAY['Web','Android','iOS','Masaüstü istemciler'],
   'tools-nextcloud-hub.png', true, false, true, 27),

  ('openstreetmap', 'OpenStreetMap · Community-powered Maps', 'tools',
   'https://www.openstreetmap.org/', 'https://www.openstreetmap.org/',
   'Collaboratively edited world map. Anonymous to use, free to embed, and improved by volunteers instead of ad-tech.',
   'Gönüllüler tarafından birlikte düzenlenen dünya haritası.',
   ARRAY['Maps','Open data','Navigation'],
   ARRAY['Haritalar','Açık veri','Navigasyon'],
   ARRAY['Web','Mobile apps via many clients'],
   ARRAY['Web','Birçok istemci üzerinden mobil uygulamalar'],
   'tools-openstreetmap.png', true, false, true, 28),

  ('cryptpad', 'CryptPad · Encrypted Docs & Boards', 'tools',
   'https://cryptpad.fr/', 'https://cryptpad.fr/',
   'Open-source, end-to-end encrypted collaboration suite: notes, docs, sheets, kanban, whiteboards and more.',
   'Notlar, belgeler, tablolar, kanban panoları, beyaz tahta sunan açık kaynaklı, uçtan uca şifreli işbirliği paketi.',
   ARRAY['Collaboration','Encrypted','Docs','Open-source'],
   ARRAY['İşbirliği','Şifreli','Belgeler','Açık kaynak'],
   ARRAY['Web'], ARRAY['Web'],
   'tools-cryptpad.png', true, false, true, 29),

  ('collabora-online', 'Collabora Online · LibreOffice in the Browser', 'tools',
   'https://www.collaboraonline.com/', 'https://www.collaboraonline.com/',
   'LibreOffice-based online office suite for documents, spreadsheets and presentations with real-time collaboration.',
   'Belgeler, tablolar ve sunumlar için gerçek zamanlı işbirliği sunan, LibreOffice tabanlı çevrimiçi ofis paketi.',
   ARRAY['Office','Collaboration','Open-source'],
   ARRAY['Ofis','İşbirliği','Açık kaynak'],
   ARRAY['Web','Self-hosted'], ARRAY['Web','Kendi sunucun'],
   'tools-collabora-online.png', true, false, true, 30),

  ('breath-aurora', 'Breath Aurora · Guided Breathing', 'wellness',
   'https://candanumut.github.io/breath-aurora/',
   'https://candanumut.github.io/breath-aurora/',
   'Calm, visual breathing guide with customizable patterns for stress relief, focus, and pre-sleep relaxation. No account, no data collection.',
   'Stres azaltma, odaklanma ve uyku öncesi rahatlama için özelleştirilebilir nefes rehberi.',
   ARRAY['Breathing','Mindfulness','Relaxation'],
   ARRAY['Nefes','Farkındalık','Rahatlama'],
   ARRAY['Web'], ARRAY['Web'],
   'wellness-breath-aurora.png', true, false, false, 31),

  ('marifah', 'Marifah · Islamic Knowledge Companion', 'spiritual',
   'https://candanumut.github.io/marifah/',
   'https://candanumut.github.io/marifah/',
   'A structured Islamic knowledge companion covering aqeedah, fiqh, seerah, and daily supplications. Designed for gradual, consistent learning.',
   'Akide, fıkıh, siyer ve günlük duaları kapsayan yapılandırılmış bir İslami ilim rehberi.',
   ARRAY['Islamic knowledge','Aqeedah','Dua','Learning'],
   ARRAY['İslami ilim','Akide','Dua','Öğrenme'],
   ARRAY['Web'], ARRAY['Web'],
   'spiritual-marifah.png', true, false, false, 32),

  ('pomodoro-circle', 'Pomodoro Circle · Focus Timer', 'tools',
   'https://candanumut.github.io/pomodoro/',
   'https://candanumut.github.io/pomodoro/',
   'Clean, distraction-free Pomodoro timer with customizable intervals. Works offline, no account required, no data sent.',
   'Özelleştirilebilir aralıklara sahip sade, dikkat dağıtmayan Pomodoro zamanlayıcısı.',
   ARRAY['Productivity','Focus','Timer','Offline'],
   ARRAY['Verimlilik','Odaklanma','Zamanlayıcı','Çevrimdışı'],
   ARRAY['Web'], ARRAY['Web'],
   'productivity-pomodoro-circle.png', true, false, false, 33)

ON CONFLICT (slug) DO NOTHING;
